# Generated by Django 4.2.7 on 2023-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
