# Generated by Django 4.2.7 on 2023-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_participants_participant_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments/%Y/%m/%d'),
        ),
    ]
